# 1. Import

In [1]:
import pandas as pd

# 2. Configuration

In [ ]:
class Configuration:
    
    label_names = [
        'Left Infraclinoid Internal Carotid Artery',
        'Right Infraclinoid Internal Carotid Artery',
        'Left Supraclinoid Internal Carotid Artery',
        'Right Supraclinoid Internal Carotid Artery',
        'Left Middle Cerebral Artery',
        'Right Middle Cerebral Artery',
        'Anterior Communicating Artery',
        'Left Anterior Cerebral Artery',
        'Right Anterior Cerebral Artery',
        'Left Posterior Communicating Artery',
        'Right Posterior Communicating Artery',
        'Basilar Tip',
        'Other Posterior Circulation',
        'Aneurysm Present',
    ]
    
CFG = Configuration()

# 2. Load DataFrame

In [3]:
train_df = pd.read_csv('../train.csv')

# 3. EDA

## 3.1 Label Distribution

In [4]:
total = []

for label_name in CFG.label_names:
    label_series = train_df[label_name]
    
    print(label_name)
    print('==================================================================')
    print('0 counts:', label_series.value_counts(dropna=False)[0])
    print('1 counts:', label_series.value_counts(dropna=False)[1])
    
    print('na counts:', label_series.isna().sum())
    
    total.append(sum(label_series == 1))

Left Infraclinoid Internal Carotid Artery
==================================================================
0 counts: 4270
1 counts: 78
na counts: 0
Right Infraclinoid Internal Carotid Artery
==================================================================
0 counts: 4250
1 counts: 98
na counts: 0
Left Supraclinoid Internal Carotid Artery
==================================================================
0 counts: 4017
1 counts: 331
na counts: 0
Right Supraclinoid Internal Carotid Artery
==================================================================
0 counts: 4071
1 counts: 277
na counts: 0
Left Middle Cerebral Artery
==================================================================
0 counts: 4129
1 counts: 219
na counts: 0
Right Middle Cerebral Artery
==================================================================
0 counts: 4054
1 counts: 294
na counts: 0
Anterior Communicating Artery
==================================================================
0 counts: 3985
1 counts: 363
na counts: 0
Left Anterior Cerebral Artery
==================================================================
0 counts: 4302
1 counts: 46
na counts: 0
Right Anterior Cerebral Artery
==================================================================
0 counts: 4292
1 counts: 56
na counts: 0
Left Posterior Communicating Artery
==================================================================
0 counts: 4262
1 counts: 86
na counts: 0
Right Posterior Communicating Artery
==================================================================
0 counts: 4247
1 counts: 101
na counts: 0
Basilar Tip
==================================================================
0 counts: 4238
1 counts: 110
na counts: 0
Other Posterior Circulation
==================================================================
0 counts: 4235
1 counts: 113
na counts: 0
Aneurysm Present
==================================================================
0 counts: 2484
1 counts: 1864
na counts: 0

In [5]:
total

[78, 98, 331, 277, 219, 294, 363, 46, 56, 86, 101, 110, 113, 1864]

In [6]:
summary_df = pd.DataFrame({
    'total': total,
}, index=CFG.label_names)

summary_df

                                            total
Left Infraclinoid Internal Carotid Artery      78
Right Infraclinoid Internal Carotid Artery     98
Left Supraclinoid Internal Carotid Artery     331
Right Supraclinoid Internal Carotid Artery    277
Left Middle Cerebral Artery                   219
Right Middle Cerebral Artery                  294
Anterior Communicating Artery                 363
Left Anterior Cerebral Artery                  46
Right Anterior Cerebral Artery                 56
Left Posterior Communicating Artery            86
Right Posterior Communicating Artery          101
Basilar Tip                                   110
Other Posterior Circulation                   113
Aneurysm Present                             1864

In [7]:
weights = []

for label_name in CFG.label_names:
    positive = summary_df.loc[label_name, 'total']
    negative = len(train_df) - positive
    weights.append(negative / positive)
    
weights

[54.743589743589745,
 43.36734693877551,
 12.13595166163142,
 14.696750902527075,
 18.85388127853881,
 13.789115646258503,
 10.977961432506888,
 93.52173913043478,
 76.64285714285714,
 49.55813953488372,
 42.04950495049505,
 38.527272727272724,
 37.47787610619469,
 1.332618025751073]

## 3.2 Non-integral Label

In [9]:
train_df['num_aneurysm'] = 0
for label_name in CFG.label_names:
    train_df['num_aneurysm'] += train_df[label_name]
    
train_df

,SeriesInstanceUID,PatientAge,PatientSex,Modality,Left Infraclinoid Internal Carotid Artery,Right Infraclinoid Internal Carotid Artery,Left Supraclinoid Internal Carotid Artery,Right Supraclinoid Internal Carotid Artery,Left Middle Cerebral Artery,Right Middle Cerebral Artery,Anterior Communicating Artery,Left Anterior Cerebral Artery,Right Anterior Cerebral Artery,Left Posterior Communicating Artery,Right Posterior Communicating Artery,Basilar Tip,Other Posterior Circulation,Aneurysm Present,num_aneurysm
0,1.2.826.0.1.3680043.8.498.10004044428023505108...,64,Female,MRA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1.2.826.0.1.3680043.8.498.10004684224894397679...,76,Female,MRA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1.2.826.0.1.3680043.8.498.10005158603912009425...,58,Male,CTA,0,0,0,0,0,0,0,0,0,0,0,0,1,1,2
3,1.2.826.0.1.3680043.8.498.10009383108068795488...,71,Male,MRA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1.2.826.0.1.3680043.8.498.10012790035410518400...,48,Female,MRA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4343,1.2.826.0.1.3680043.8.498.99915610493694667606...,62,Female,MRI T1post,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4344,1.2.826.0.1.3680043.8.498.99920680741054836990...,76,Female,MRA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4345,1.2.826.0.1.3680043.8.498.99953513260518059135...,44,Female,CTA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4346,1.2.826.0.1.3680043.8.498.99982144859397209076...,58,Female,MRI T2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4347,1.2.826.0.1.3680043.8.498.99985209798463601651...,65,Female,CTA,0,0,0,0,1,0,0,0,0,0,0,0,0,1,2

In [ ]:
train_df['integral'] = False
train_df['integral'] = \
    ((train_df['num_aneurysm'] > 0) & (train_df['Aneurysm Present'] == 1)) |\
    ((train_df['num_aneurysm'] == 0) & (train_df['Aneurysm Present'] == 0))

train_df['integral'].value_counts()

integral
True    4348
Name: count, dtype: int64